<?php

namespace ContainerOenjwzm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CXm73WbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cXm73Wb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cXm73Wb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'utilisateur' => ['privates', '.errored..service_locator.cXm73Wb.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.cXm73Wb": it references class "App\\Entity\\User" but no such service exists.'],
        ], [
            'utilisateur' => 'App\\Entity\\User',
        ]);
    }
}
