<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2kWXdWZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2kWXdWZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2kWXdWZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2kWXdWZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2kWXdWZ\App_KernelDevDebugContainer([
    'container.build_hash' => '2kWXdWZ',
    'container.build_id' => '8d842928',
    'container.build_time' => 1709501315,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2kWXdWZ');
