<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQwJBvEy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQwJBvEy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQwJBvEy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQwJBvEy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQwJBvEy\App_KernelDevDebugContainer([
    'container.build_hash' => 'QwJBvEy',
    'container.build_id' => '71fbb6ff',
    'container.build_time' => 1707584500,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQwJBvEy');
